spring.application.name=smart-campus-backend
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/smart_campus_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 (Google) Configuration
spring.security.oauth2.client.registration.google.client-id=256860756054-q9cc98qug6bthnqcireo0iv1lhbiafuv.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# App Security Mapping
app.security.admin-emails=kavindu2002nethmina@gmail.com,shehanmadusanka775@gmail.com,shakyasandali039@gmail.com,Sachininisansala320@gmail.com
app.oauth2.frontend-success-url=http://localhost:5173
app.cors.allowed-origins=http://localhost:5173

# Logging
logging.level.root=INFO
logging.level.com.it3030.backend=DEBUG
